### PR TITLE
Upgrade RisePlayer (restart external logging) and RiseCache (add User-Agent headers)

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino :+1:

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani Updated to include new .json files

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
