### PR TITLE
Do not update components on Ubuntu 12.04 and 12.10

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
Instead of looking for different unsupported versions of 12, why not check directly for 14.04

**Comment by fjvallarino** [comment]
@tejohnso I thought about that but, based on what @mfisher11 said, the issue only exists with the 12.x releases. But yes, maybe we should just check for version >= 14.04.

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
@tejohnso Updated to exclude versions before 14.04. Please review

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
