### PR TITLE
Upgrade Chrome to 49.0.2623.110 on Latest channel and set 2% rollout

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino are we going to upgrade the V3 displays as well?

**Comment by fjvallarino** [comment]
@ahmedalsudani I have already updated the packages in GCS; they will be used the next time we build a bundle (we don't need to modify config files for those)

**Comment by ahmedalsudani** [comment]
Oh right! I forgot we bundle things now :smile: 

:+1:

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani I'll merge tomorrow before deployment

**Pull request merged**
