### PR TITLE
Set 50% rollout for all but win32

### PR DESCRIPTION
**Pull request by tejohnso**
@ahmedalsudani @fjvallarino please review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@tejohnso we usually modify the json files along with the cfg files. Is there a reason we're not doing it this time?

**Comment by fjvallarino** [comment]
:+1:

**Comment by tejohnso** [comment]
@ahmedalsudani Those cfg files aren't being used anymore.  Ver3 installer uses json.  There's really no reason to keep the electron-remote.....cfg files around.  I'll remove them in another pr.

**Comment by ahmedalsudani** [comment]
:+1:

**Pull request merged**
