### PR TITLE
Set new cache version at 2%

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino @ahmedalsudani please review

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso Currently rollout is set at 50% on production, mainly for the installer released yesterday. If we lower it now to 2%, we will be delaying that update (unless all existing v3 installers have already upgraded). Is this correct?

Other than that, :+1:

**Comment by tejohnso** [comment]
@fjvallarino Doesn't the installer ignore the %?

**Comment by fjvallarino** [comment]
@tejohnso Oh, yeah, we had this same discussion yesterday :(

**Comment by ahmedalsudani** [comment]
:+1:

**Pull request merged**
