### PR TITLE
Set BundleURL so upgrades can be tested

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino @ahmedalsudani please review.

### CODE REVIEW

**Comment by fjvallarino** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
:+1:

**Comment by tejohnso** [comment]
@fjvallarino @ahmedalsudani changed as per previous discussion.

**Comment by ahmedalsudani** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Comment by tejohnso** [comment]
@ahmedalsudani @fjvallarino Another update :)

**Comment by ahmedalsudani** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
