### PR TITLE
Upgrade to Chrome 47.0.2526.80

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Comment by tejohnso** [comment]
@fjvallarino Wasn't this deployed?

**Comment by fjvallarino** [comment]
@tejohnso Yes, I forgot to merge it (we don't have CI on this one, so files are actually deployed manually)

**Pull request merged**
